# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12wIQXq-2jl5xHedHN1DHNYliUomSuMO0
"""

a = int(input())
b = int(input())
if (a > 999 and a < 10000) and (b > 999 and b < 10000) and a < b:
  for i in range(a, b + 1):
    y = i // 1000 
    g = (i // 100) % 10
    q = (((i // 10) % 100) % 10)
    r = (((i % 1000) % 100) % 10)
    if (y == r) and (q == g):
      print(i)
else:
  print("Print 2 4-digit numbers ")