# -*- coding: utf-8 -*-
"""range.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x1CrWxbsyMcPnfYmRuh-7VDCYJsjPmk3
"""

print("введите первое число")
a = int(input())
print("введите второе число")
b = int(input())
if (a <= b):
  for i in range(a,b):
    print(i)
  print(b)
else:
  for i in range(a, b - 1, -1):
    print(i)